### ISSUE TITLE
read_hiragana_file.py__Character type

### ISSUE THREAD

**Issue by amanotaiga** [yukoba/CnnJapaneseCharacter#2]
Hi,I have a question about **read_hiragana_file.py**
`Character type = 72, person = 160, y = 127, x = 128`
What does `Character type` means?
And is `nb_classes` the same as `Character Type`?
Thanks.

**Comment by yukoba** [comment]
> And is nb_classes the same as Character Type?

Yes.

**Comment by amanotaiga** [comment]
Excuse me.What does Character type means?
Cause l saw there are 75 hiragana on the etl website

**Comment by yukoba** [comment]
`if b'.HIRA' in r[2]` is 72.

**Comment by yukoba** [comment]
Maybe 3 of these 5 might be hiragana too.

```
b'CYUU.HIR'
b'SYUU.HIR'
b'KAKU.HIR'
b'HAKU.HIR'
b'O.WO.HIR'
```

**Comment by amanotaiga** [comment]
So use 72 or 75 wouldn't affect the result?
Cause 72 doesn't appear on the website.How did you get this number?
Thanks

**Comment by yukoba** [comment]
> So use 72 or 75 wouldn't affect the result?

I think it is a trivial problem.
If it is for a product, please search missing 3 characters.

> How did you get this number?

Just count `if b'.HIRA' in r[2]`.
